version: "3.9"

services:
  ms-post:
    container_name: ms-post
    build:
      context: .
      dockerfile: Dockerfile
    image: pee-java_app:1.0.0
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/ms-auth
      - DATABASE_USERNAME=ms-post
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    restart: unless-stopped

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ms-auth
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-post
    volumes:
      - java_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  java_db_data:
